### ISSUE TITLE
predict.py does not perform inverse normalization when no Y is supplied

### ISSUE THREAD

**Issue by das22** [melloddy/SparseChem#5]
When running predict.py on regression/hybrid models with new compounds (e.g. suppling only a new X matrix), predict.py does not respect "inverse_normalization 1". This seems related to Ys being None causing the first part of this code to run

```
else:
        if args.y_class is None and args.y_regr is None:
            class_out, regr_out = sc.predict_dense(net, loader_te, dev=dev, dropout=args.dropout, progress=True, y_cat_columns=select_cat_ids)
        else:
            class_out, regr_out = sc.predict_sparse(net, loader_te, dev=dev, dropout=args.dropout, progress=True, y_cat_columns=select_cat_ids)
            if args.inverse_normalization == 1:
               regr_out = sc.inverse_normalization(regr_out, mean=np.array(stats["mean"]), variance=np.array(stats["var"]), array=True)
```

**Comment by molden** [comment]
@das22 implementing the inverse normalisation for dense predictions in branch https://github.com/melloddy/SparseChem/tree/5-predict-inverse-normalization . Would it be possible to test if it gives some sensible values?

**Comment by das22** [comment]
@molden The values do indeed look reasonable! I'm no longer seeing negative numbers, the predictions reach larger values and the range is similar to my input training values.

**Comment by AnsgarSchuffenhauer** [comment]
@molden Are you going integrate this into master now?

**Comment by AnsgarSchuffenhauer** [comment]
Just out of curiosity: Wuld for the dense case the inversomalization be nut a lot easier by simply multiplying the numpy array with the 1-D numpy array of standard deviation, and the add the 1-D numpy array of means, relying on numpy's broadcasting abilities?

**Comment by molden** [comment]
@AnsgarSchuffenhauer yes you are right this is easier. I will have a look to optimise this before merging into master.
